# Docker Compose file to start a full RECYCLUS node.
#
# Required env variables:
#
# RECYCLUS_CONFIG : points to the root RECYCLUS configuration directory
#       example: export RECYCLUS_CONFIG=/Users/yarden/RECYCLUS_CONFIG
# RECYCLUS_HOSTNAME: HostName or IP address for apache httpd front-end server
#       example: export RECYCLUS_HOSTNAME=my.recyclus.node
#       example: export RECYCLUS_HOSTNAME=`docker-machine ip`
# RECYCLUS_VERSION: version of RECYCLUS/Docker distribution
#       example: export RECYCLUS_VERSION=1.0

version: "3.4"

services:
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    networks:
      - cyclus

  batch:
    image: ${RECYCLUS_HUB}/recyclus-batch:${RECYCLUS_VERSION-latest}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    networks:
      - cyclus

  worker:
    image: ${RECYCLUS_HUB}/recyclus-worker:${RECYCLUS_VERSION-latest}
    depends_on:
      - redis
    networks:
      - cyclus

  datastore:
    image: ${RECYCLUS_HUB}/recyclus-datastore:${RECYCLUS_VERSION-latest}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /recyclus/secrets/mongo-admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /recyclus/secrets/mongo-password
    volumes:
      - "$RECYCLUS_CONFIG/secrets/mongo-password:/recyclus/secrets/mongo-password:ro"
      - "$RECYCLUS_CONFIG/secrets/mongo-admin:/recyclus/secrets/mongo-admin:ro"
      - datastore-files:/files
    depends_on:
      - datastore-db
    networks:
      - cyclus

  datastore-db:docker
    image: "mongo:latest"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /recyclus/secrets/mongo-admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /recyclus/secrets/mongo-password
    volumes:
      - "$RECYCLUS_CONFIG/secrets/mongo-password:/recyclus/secrets/mongo-password:ro"
      - "$RECYCLUS_CONFIG/secrets/mongo-admin:/recyclus/secrets/mongo-admin:ro"
      - datastore-info:/data/db
    networks:
      - cyclus

  gateway:
    image: ${RECYCLUS_HUB}/recyclus-gateway:${RECYCLUS_VERSION-latest}
    ports:
      - "5000:80"
    environment:
      JWT_SECRET_KEY_FILE: /recyclus/secrets/jwt-key
    volumes:
      - "$RECYCLUS_CONFIG/certificates/hostcert:/recyclus/certificates/:ro"
      - "$RECYCLUS_CONFIG/secrets/gateway-password:/recyclus/secrets/gateway-password:ro"
      - "$RECYCLUS_CONFIG/secrets/jwt-key:/recyclus/secrets/jwt-key:ro"
      - gateway-db:/data
    networks:
      - cyclus
    depends_on:
      - redis
      - batch
      - datastore

networks:
  cyclus:

volumes:
  redis:
  gateway-db:
  datastore-files:
  datastore-info:
