version: "3.3"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - ./repositories/redis:/data
    networks:
      - cyclus

  batch:
    image: ylivnat/recyclus-batch
    env_file:
      - ./env/batch.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    networks:
      - cyclus

  worker:
    image: ylivnat/recyclus-worker
    depends_on:
      - redis
    networks:
      - cyclus

  datastore:
    image: ylivnat/recyclus-datastore
    env_file:
      - ./env/datastore.env
    volumes:
      - ./repositories/datastore/files:/files
    depends_on:
      - datastore-db
    networks:
      - cyclus

  datastore-db:
    image: "mongo:latest"
    restart: always
    env_file:
      - ./env/datastore-db.env
    volumes:
      - ./repositories/datastore/db:/data/db
    networks:
      - cyclus

  gateway:
    image: ylivnat/recyclus-gateway
    env_file:
      - env/gateway.env
    ports:
      - "5000:5000"
    volumes:
      - ./repositories/gateway:/data
    networks:
      - cyclus
    depends_on:
      - redis
      - batch
      - datastore

networks:
  cyclus:
