version: "3.3"
services:
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - ./repositories/redis:/data
    networks:
      - cyclus
    deploy:
      placement:
        constraints: [node.role == manager]

  batch:
    image: ylivnat/recyclus-batch
    environment:
      - FLASK_ENV
    env_file:
      - ./env/batch.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    networks:
      - cyclus

  worker:
    image: ylivnat/recyclus-worker
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - redis
    networks:
      - cyclus

  datastore:
    image: ylivnat/recyclus-datastore
    environment:
      - FLASK_ENV
    env_file:
      - ./env/datastore.env
    volumes:
      - ./repositories/datastore/files:/files
    depends_on:
      - datastore-db
    networks:
      - cyclus

  datastore-db:
    image: "mongo:latest"
    env_file:
      - ./env/datastore-db.env
    volumes:
      - ./repositories/datastore/db:/data/db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    networks:
      - cyclus

  gateway:
    image: ylivnat/recyclus-gateway
    environment:
      - FLASK_ENV
    env_file:
      - env/gateway.env
    ports:
      - "5000:5000"
    volumes:
      - ./repositories/gateway:/data
    networks:
      - cyclus
    depends_on:
      - redis
      - batch
      - datastore
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  cyclus:
