#!/bin/bash

set -eo pipefail

source "$(dirname "$(realpath "$0")")/functions.sh"

#####
## This script generates random secrets for the various passwords and secret keys
## that are required for an Recyclus deployment.
#####

SECRETS="/recyclus/secrets"
mkdir -p "$SECRETS"

info "Generating required secrets"

function create_secret {
    # First argument is secret name
    # Second argument is length, with default of 20
    [ -z "$1" ] && error "create_secret: Secret name must be given"
    if [ -f "$SECRETS/$1" ]; then
        warn "Secret '$1' already exists"
    else
        echo -n "$(tr -dc '[:alnum:]' < /dev/urandom | head -c "${2:-20}")" > "$SECRETS/$1"
        info "Created new secret '$1'"
    fi
}

function create_mongo_init {
	if [ -f "$SECRETS/mongo-init" ]; then
		warn "Secret mongo-init already exists"
	else
		echo "create mongo init"
		echo -en "MONGO_INITDB_ROOT_USERNAME=admin\nMONGO_INITDB_ROOT_PASSWORD=" > "$SECRETS/mongo-init"
		cat  "$SECRETS/datastore-password" >> "$SECRETS/mongo-init"
		echo >> "$SECRETS/mongo-init"
	fi
}


# Passwords
create_secret "gateway-password"
create_secret "datastore-password"
create_mongo_init


# Secret keys
create_secret "jwt-key" 100


info "Done"