DockerfileARG PYTHON_VERSION=3.7.0-alpine3.8

FROM python:${PYTHON_VERSION}
ENV PYTHONUNBUFFERED 1
RUN apk add --no-cache \
            --upgrade \
            --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
        alpine-sdk

COPY ./requirements /tmp/requirements
RUN pip install -U pip \
    && pip install -r /tmp/requirements/dev.txt

WORKDIR /code
#COPY ./cyclus_gateway instance *.db manage.py /code/
COPY . /code

EXPOSE 5000



